// src/socket/handler.ts

// Server = the whole socket.io server (io)
// Socket = one single connected user
import { Server, Socket } from "socket.io"

// Import all our state and helper functions
import {
  checkboxes,
  users,
  activityLogs,
  isOnCooldown,
  getCoolDownRemaining,
  setCoolDown,
  addActivity,
  TOTAL_CHECKBOXES
} from "../store/state"

import { checkboxChangePayload, ActivityLog } from "../types"


// This function is called once per connected user
// io   = entire server (can talk to everyone)
// socket = this specific user's connection
export function registerSocketHandlers(io: Server, socket: Socket) {


  // ── user:join ──────────────────────────────────────────
  // Frontend emits this when user enters their name
  // and clicks join button
  socket.on("user:join", (username: string) => {

    // typeof check because frontend could send anything
    // .trim() removes spaces from start and end
    // "  john  " becomes "john"
    if (!username || typeof username !== "string" || username.trim() === "") {
      // socket.emit sends ONLY to this user
      socket.emit("error", { message: "Invalid username" })
      return   // stop here, don't continue
    }

    // Save this socket's username
    // socket.id is auto-generated by socket.io
    // example: "HlF3kP2mXqR8vN1j"
    users[socket.id] = username.trim()

    // socket.emit = send to THIS user only
    // We send the FULL current state
    // so new user sees what others already clicked
    socket.emit("state:init", {
      checkboxes: Array.from(checkboxes.values()),
      // Array.from converts Map to array
      // Map { 0: {...}, 1: {...} } → [{...}, {...}]
      // Frontend needs array not Map
      activityLogs,
      totalCheckboxes: TOTAL_CHECKBOXES
    })

    // io.emit = send to EVERYONE including this user
    // So all users see updated online count
    io.emit("user:joined", {
      username: username.trim(),
      onlineCount: Object.keys(users).length
      // Object.keys gives array of all socket IDs
      // .length = how many users online
    })
  })


  // ── checkbox:change ────────────────────────────────────
  // Frontend emits this every time user clicks a checkbox
  socket.on("checkbox:change", (payload: checkboxChangePayload) => {

    const { id, checked } = payload
    // Destructuring = pull id and checked out of payload object
    // Same as: const id = payload.id; const checked = payload.checked

    const username = users[socket.id]
    // Look up who this socket belongs to

    // Security check — what if someone emits without joining?
    if (!username) {
      socket.emit("error", { message: "Please join first" })
      return
    }

    // Validate id range
    // Frontend could send id = -1 or id = 9999 (doesn't exist)
    if (id < 0 || id >= TOTAL_CHECKBOXES) {
      socket.emit("error", { message: "Invalid checkbox" })
      return
    }

    // THE COOLDOWN CHECK
    // This is what stops rapid clicking
    if (isOnCooldown(id)) {
      const remaining = getCoolDownRemaining(id)

      // Only tell THIS user — nobody else cares
      socket.emit("checkbox:cooldown", {
        id,
        remaining,          // frontend uses this for countdown
        message: `Wait ${Math.ceil(remaining / 1000)}s`
        // Math.ceil rounds UP
        // 2400ms → 3 seconds (not 2.4 seconds)
      })
      return  // STOP — don't update anything
    }

    // Update the checkbox in our state
    checkboxes.set(id, {
      id,
      checked,
      lastClickedBy: username,
    lastClickedAt: Date.now()
    })

    // Start the 3 second cooldown for this checkbox
    setCoolDown(id)

    // Build the activity log entry
    const log: ActivityLog = {
      username,
      checkboxId: id,
      action: checked ? "checked" : "unchecked",
      // ternary = if checked is true → "checked" else "unchecked"
      timestamp: Date.now()
    }

    // Save to our activity log array
    addActivity(log)

    // Tell EVERYONE the checkbox changed
    // io.emit = ALL users see the update in real time
    io.emit("checkbox:updated", {
      id,
      checked,
      lastClickedBy: username,
      lastClickedAt: Date.now(),
      cooldownMs: 3000
    })

    // Tell EVERYONE about the new activity
    // This updates the sidebar for all users
    io.emit("activity:new", log)
  })


  // ── disconnect ─────────────────────────────────────────
  // Socket.io fires this automatically when user
  // closes tab, loses internet, or refreshes
  socket.on("disconnect", () => {
    const username = users[socket.id]

    // Only do something if this socket had a username
    // (user might disconnect before joining)
    if (username) {
      // Remove from users map
      // If we don't do this, ghost users stay forever
      delete users[socket.id]

      // Tell everyone this user left
      io.emit("user:left", {
        username,
        onlineCount: Object.keys(users).length
      })
    }
  })
}